-- ============================================================================
-- HAXEUS — Full Database Reset & Rebuild
-- Generated from complete codebase scan on 2026-03-08
-- Fixed ordering: Phase 3a creates ALL tables, Phase 3b creates ALL policies
-- ============================================================================
-- WARNING: This will DROP ALL TABLES and recreate from scratch.
-- Run this in the Supabase SQL Editor. Do NOT auto-execute.
-- ============================================================================

-- ─── PHASE 0: Drop Django Remnants ──────────────────────────────────────────
DROP TABLE IF EXISTS public.authtoken_token CASCADE;
DROP TABLE IF EXISTS public.django_admin_log CASCADE;
DROP TABLE IF EXISTS public.django_session CASCADE;
DROP TABLE IF EXISTS public.auth_group_permissions CASCADE;
DROP TABLE IF EXISTS public.auth_permission CASCADE;
DROP TABLE IF EXISTS public.auth_group CASCADE;
DROP TABLE IF EXISTS public.django_content_type CASCADE;
DROP TABLE IF EXISTS public.django_migrations CASCADE;

-- ─── PHASE 1: Drop Views ───────────────────────────────────────────────────
DROP VIEW IF EXISTS public.low_stock_products CASCADE;
DROP VIEW IF EXISTS public.top_selling_products CASCADE;
DROP VIEW IF EXISTS public.products_with_ratings CASCADE;

-- ─── PHASE 2: Drop All Tables (reverse FK order) ───────────────────────────
DROP TABLE IF EXISTS public.review_images CASCADE;
DROP TABLE IF EXISTS public.review_votes CASCADE;
DROP TABLE IF EXISTS public.return_items CASCADE;
DROP TABLE IF EXISTS public.return_requests CASCADE;
DROP TABLE IF EXISTS public.coupon_usage CASCADE;
DROP TABLE IF EXISTS public.loyalty_transactions CASCADE;
DROP TABLE IF EXISTS public.loyalty_points CASCADE;
DROP TABLE IF EXISTS public.analytics_events CASCADE;
DROP TABLE IF EXISTS public.order_items CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.cart_items CASCADE;
DROP TABLE IF EXISTS public.saved_for_later CASCADE;
DROP TABLE IF EXISTS public.wishlist CASCADE;
DROP TABLE IF EXISTS public.product_reviews CASCADE;
DROP TABLE IF EXISTS public.product_images CASCADE;
DROP TABLE IF EXISTS public.product_videos CASCADE;
DROP TABLE IF EXISTS public.product_inventory CASCADE;
DROP TABLE IF EXISTS public.product_relations CASCADE;
DROP TABLE IF EXISTS public.product_views CASCADE;
DROP TABLE IF EXISTS public.price_changes CASCADE;
DROP TABLE IF EXISTS public.search_queries CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.coupons CASCADE;
DROP TABLE IF EXISTS public.user_addresses CASCADE;
DROP TABLE IF EXISTS public.user_roles CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public.store_settings CASCADE;
DROP TABLE IF EXISTS public.email_queue CASCADE;
DROP TABLE IF EXISTS public.email_templates CASCADE;
DROP TABLE IF EXISTS public.email_campaigns CASCADE;
DROP TABLE IF EXISTS public.newsletter_subscribers CASCADE;
DROP TABLE IF EXISTS public.abandoned_carts CASCADE;
DROP TABLE IF EXISTS public.audit_log CASCADE;

-- Drop existing functions
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
DROP FUNCTION IF EXISTS public.increment_coupon_usage(text) CASCADE;
DROP FUNCTION IF EXISTS public.increment_coupon_usage(uuid) CASCADE;
DROP FUNCTION IF EXISTS public.reserve_product_stock(bigint, text, integer) CASCADE;
DROP FUNCTION IF EXISTS public.release_product_stock(bigint, text, integer) CASCADE;
DROP FUNCTION IF EXISTS public.decrement_inventory_rpc(bigint, text, integer) CASCADE;
DROP FUNCTION IF EXISTS public.increment_inventory(bigint, text, integer) CASCADE;
DROP FUNCTION IF EXISTS public.update_review_helpful_count(uuid, boolean, integer) CASCADE;
DROP FUNCTION IF EXISTS public.increment_abandoned_cart_emails(uuid) CASCADE;


-- ============================================================================
-- PHASE 3a: CREATE ALL TABLES + ENABLE RLS + INDEXES
-- No CREATE POLICY statements in this block.
-- Tables are ordered so FK references always point to already-created tables.
-- ============================================================================

-- ──────────────────────────────────────────────────────────────────────────────
-- 1. products
-- Used by: lib/services.ts, lib/search.ts, lib/recommendations.ts,
--          lib/queries/products.ts, CartContext.tsx, admin/products/page.tsx,
--          app/api/payment/create-order/route.ts
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    description text,
    price numeric NOT NULL,
    front_image text,
    back_image text,
    available_sizes text[] DEFAULT ARRAY['S','M','L','XL'],
    colors text[] DEFAULT ARRAY['Black','White'],
    total_stock integer DEFAULT 100,
    category text DEFAULT 'apparel',
    slug text UNIQUE,
    is_active boolean DEFAULT true,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now()
);
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_products_slug ON public.products(slug);

-- ──────────────────────────────────────────────────────────────────────────────
-- 2. profiles
-- Used by: admin/users/page.tsx, abandoned-cart.ts, cron/abandoned-carts
-- Synced from auth.users via trigger
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.profiles (
    id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email text NOT NULL,
    full_name text,
    avatar_url text,
    role text DEFAULT 'customer',
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- ──────────────────────────────────────────────────────────────────────────────
-- 3. user_roles
-- Used by: lib/admin.ts, analytics/route.ts, admin guard in multiple routes
-- CRITICAL: Must exist before any policy references it
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.user_roles (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    user_id uuid UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    role text NOT NULL DEFAULT 'customer',
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now()
);
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- ──────────────────────────────────────────────────────────────────────────────
-- 4. user_addresses
-- Used by: checkout, create-order/route.ts, lib/services.ts
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.user_addresses (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name text NOT NULL,
    phone text NOT NULL,
    address_line1 text NOT NULL,
    address_line2 text,
    city text NOT NULL,
    state text NOT NULL,
    pincode text NOT NULL,
    is_default boolean DEFAULT false,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now()
);
ALTER TABLE public.user_addresses ENABLE ROW LEVEL SECURITY;

-- ──────────────────────────────────────────────────────────────────────────────
-- 5. product_images
-- Used by: lib/queries/products.ts, admin/products/page.tsx, product detail pages
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.product_images (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    product_id bigint REFERENCES public.products(id) ON DELETE CASCADE,
    image_url text NOT NULL,
    display_order integer DEFAULT 0,
    is_primary boolean DEFAULT false,
    created_at timestamp DEFAULT now()
);
ALTER TABLE public.product_images ENABLE ROW LEVEL SECURITY;

-- ──────────────────────────────────────────────────────────────────────────────
-- 6. product_videos
-- Used by: product detail pages
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.product_videos (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    product_id bigint REFERENCES public.products(id) ON DELETE CASCADE,
    video_url text NOT NULL,
    video_type text DEFAULT 'demo',
    thumbnail_url text,
    created_at timestamp DEFAULT now()
);
ALTER TABLE public.product_videos ENABLE ROW LEVEL SECURITY;

-- ──────────────────────────────────────────────────────────────────────────────
-- 7. product_inventory
-- Used by: lib/inventory.ts, create-order/route.ts, verify/route.ts
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.product_inventory (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    product_id bigint REFERENCES public.products(id) ON DELETE CASCADE,
    size text NOT NULL,
    color text DEFAULT 'default',
    stock_quantity integer NOT NULL DEFAULT 0,
    low_stock_threshold integer DEFAULT 10,
    reserved_quantity integer DEFAULT 0,
    sold_quantity integer DEFAULT 0,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now()
);
ALTER TABLE public.product_inventory ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_inventory_product_size ON public.product_inventory(product_id, size);

-- ──────────────────────────────────────────────────────────────────────────────
-- 8. cart_items
-- Used by: CartContext.tsx, abandoned-cart.ts
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.cart_items (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    product_id bigint REFERENCES public.products(id) ON DELETE CASCADE,
    size text NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now()
);
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_cart_items_user ON public.cart_items(user_id);

-- ──────────────────────────────────────────────────────────────────────────────
-- 9. orders
-- Used by: create-order/route.ts, verify/route.ts, webhooks/razorpay,
--          admin/orders, admin/page.tsx, analytics/route.ts, lib/returns.ts
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.orders (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id),
    total_amount numeric NOT NULL,
    status text DEFAULT 'pending',
    shipping_address jsonb,
    shipping_name text,
    shipping_email text,
    order_number text,
    coupon_code text,
    discount_amount numeric DEFAULT 0,
    loyalty_points_used integer DEFAULT 0,
    loyalty_points_earned integer DEFAULT 0,
    tracking_number text,
    shipping_carrier text,
    estimated_delivery_date date,
    delivered_at timestamp,
    payment_status text DEFAULT 'pending',
    payment_method text,
    razorpay_order_id text,
    razorpay_payment_id text,
    payment_verified_at timestamptz,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now()
);
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE UNIQUE INDEX idx_orders_order_number ON public.orders(order_number) WHERE order_number IS NOT NULL;
CREATE INDEX idx_orders_user ON public.orders(user_id);
CREATE INDEX idx_orders_razorpay ON public.orders(razorpay_order_id);
CREATE INDEX idx_orders_status ON public.orders(status);
CREATE INDEX idx_orders_created ON public.orders(created_at);

-- ──────────────────────────────────────────────────────────────────────────────
-- 10. order_items
-- Used by: create-order/route.ts, admin/page.tsx, lib/recommendations.ts,
--          lib/returns.ts, admin/orders
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.order_items (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    order_id uuid REFERENCES public.orders(id) ON DELETE CASCADE,
    product_id bigint REFERENCES public.products(id),
    size text NOT NULL,
    quantity integer NOT NULL,
    price numeric NOT NULL,
    created_at timestamp DEFAULT now()
);
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_order_items_order ON public.order_items(order_id);
CREATE INDEX idx_order_items_product ON public.order_items(product_id);

-- ──────────────────────────────────────────────────────────────────────────────
-- 11. coupons
-- Used by: lib/coupons.ts, coupons/validate/route.ts, admin/coupons/page.tsx,
--          create-order/route.ts
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.coupons (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    code text UNIQUE NOT NULL,
    description text DEFAULT '',
    discount_type text NOT NULL,
    discount_value numeric NOT NULL,
    min_purchase_amount numeric DEFAULT 0,
    max_discount_amount numeric,
    usage_limit integer,
    used_count integer DEFAULT 0,
    valid_from timestamp DEFAULT now(),
    valid_until timestamp,
    is_active boolean DEFAULT true,
    created_at timestamp DEFAULT now()
);
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_coupons_code ON public.coupons(code);

-- ──────────────────────────────────────────────────────────────────────────────
-- 12. coupon_usage
-- Used by: lib/coupons.ts, verify/route.ts
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.coupon_usage (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    coupon_id uuid REFERENCES public.coupons(id),
    user_id uuid REFERENCES auth.users(id),
    order_id uuid REFERENCES public.orders(id),
    discount_amount numeric,
    created_at timestamp DEFAULT now()
);
ALTER TABLE public.coupon_usage ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_coupon_usage_user ON public.coupon_usage(user_id);
CREATE INDEX idx_coupon_usage_coupon ON public.coupon_usage(coupon_id);

-- ──────────────────────────────────────────────────────────────────────────────
-- 13. wishlist
-- Used by: lib/wishlist.ts
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.wishlist (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    product_id bigint REFERENCES public.products(id) ON DELETE CASCADE,
    notify_price_drop boolean DEFAULT true,
    notify_back_in_stock boolean DEFAULT true,
    price_at_addition numeric,
    created_at timestamp DEFAULT now()
);
ALTER TABLE public.wishlist ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_wishlist_user ON public.wishlist(user_id);

-- ──────────────────────────────────────────────────────────────────────────────
-- 14. product_reviews
-- Used by: lib/reviews.ts, admin/reviews/page.tsx
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.product_reviews (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    product_id bigint REFERENCES public.products(id) ON DELETE CASCADE,
    user_id uuid REFERENCES auth.users(id),
    order_id uuid REFERENCES public.orders(id),
    rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
    title text,
    comment text,
    verified_purchase boolean DEFAULT false,
    helpful_count integer DEFAULT 0,
    not_helpful_count integer DEFAULT 0,
    is_approved boolean DEFAULT true,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now()
);
ALTER TABLE public.product_reviews ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_reviews_product ON public.product_reviews(product_id);

-- ──────────────────────────────────────────────────────────────────────────────
-- 15. review_images
-- Used by: lib/reviews.ts
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.review_images (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    review_id uuid REFERENCES public.product_reviews(id) ON DELETE CASCADE,
    image_url text NOT NULL,
    created_at timestamp DEFAULT now()
);
ALTER TABLE public.review_images ENABLE ROW LEVEL SECURITY;

-- ──────────────────────────────────────────────────────────────────────────────
-- 16. review_votes
-- Used by: lib/reviews.ts
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.review_votes (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    review_id uuid REFERENCES public.product_reviews(id) ON DELETE CASCADE,
    user_id uuid REFERENCES auth.users(id),
    is_helpful boolean NOT NULL,
    created_at timestamp DEFAULT now()
);
ALTER TABLE public.review_votes ENABLE ROW LEVEL SECURITY;

-- ──────────────────────────────────────────────────────────────────────────────
-- 17. product_relations
-- Used by: lib/recommendations.ts
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.product_relations (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    product_id bigint REFERENCES public.products(id) ON DELETE CASCADE,
    related_product_id bigint REFERENCES public.products(id) ON DELETE CASCADE,
    relation_type text NOT NULL,
    score numeric DEFAULT 0,
    created_at timestamp DEFAULT now(),
    UNIQUE(product_id, related_product_id, relation_type)
);
ALTER TABLE public.product_relations ENABLE ROW LEVEL SECURITY;

-- ──────────────────────────────────────────────────────────────────────────────
-- 18. product_views
-- Used by: lib/recommendations.ts
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.product_views (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    product_id bigint REFERENCES public.products(id) ON DELETE CASCADE,
    user_id uuid REFERENCES auth.users(id),
    session_id text,
    created_at timestamp DEFAULT now()
);
ALTER TABLE public.product_views ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_product_views_product ON public.product_views(product_id);
CREATE INDEX idx_product_views_user ON public.product_views(user_id);

-- ──────────────────────────────────────────────────────────────────────────────
-- 19. price_changes
-- Used by: lib/services.ts NotificationService
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.price_changes (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    product_id bigint REFERENCES public.products(id) ON DELETE CASCADE,
    old_price numeric,
    new_price numeric,
    change_percentage numeric,
    created_at timestamp DEFAULT now()
);
ALTER TABLE public.price_changes ENABLE ROW LEVEL SECURITY;

-- ──────────────────────────────────────────────────────────────────────────────
-- 20. loyalty_points
-- Used by: lib/loyalty.ts
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.loyalty_points (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    user_id uuid UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
    total_points integer DEFAULT 0,
    lifetime_points integer DEFAULT 0,
    tier text DEFAULT 'bronze',
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now()
);
ALTER TABLE public.loyalty_points ENABLE ROW LEVEL SECURITY;

-- ──────────────────────────────────────────────────────────────────────────────
-- 21. loyalty_transactions
-- Used by: lib/loyalty.ts, lib/services.ts LoyaltyService
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.loyalty_transactions (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id),
    points integer NOT NULL,
    transaction_type text NOT NULL,
    order_id uuid REFERENCES public.orders(id),
    description text,
    created_at timestamp DEFAULT now()
);
ALTER TABLE public.loyalty_transactions ENABLE ROW LEVEL SECURITY;

-- ──────────────────────────────────────────────────────────────────────────────
-- 22. return_requests
-- Used by: lib/returns.ts
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.return_requests (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    order_id uuid REFERENCES public.orders(id),
    user_id uuid REFERENCES auth.users(id),
    return_type text NOT NULL,
    reason text NOT NULL,
    details text,
    status text DEFAULT 'pending',
    refund_amount numeric,
    admin_notes text,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now()
);
ALTER TABLE public.return_requests ENABLE ROW LEVEL SECURITY;

-- ──────────────────────────────────────────────────────────────────────────────
-- 23. return_items
-- Used by: lib/returns.ts
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.return_items (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    return_request_id uuid REFERENCES public.return_requests(id) ON DELETE CASCADE,
    order_item_id uuid REFERENCES public.order_items(id),
    quantity integer NOT NULL,
    exchange_size text,
    created_at timestamp DEFAULT now()
);
ALTER TABLE public.return_items ENABLE ROW LEVEL SECURITY;

-- ──────────────────────────────────────────────────────────────────────────────
-- 24. saved_for_later
-- Used by: lib/abandoned-cart.ts
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.saved_for_later (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
    product_id bigint REFERENCES public.products(id) ON DELETE CASCADE,
    size text,
    created_at timestamp DEFAULT now()
);
ALTER TABLE public.saved_for_later ENABLE ROW LEVEL SECURITY;

-- ──────────────────────────────────────────────────────────────────────────────
-- 25. search_queries
-- Used by: lib/search.ts
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.search_queries (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    query text NOT NULL,
    user_id uuid REFERENCES auth.users(id),
    results_count integer DEFAULT 0,
    clicked_product_id bigint REFERENCES public.products(id),
    created_at timestamp DEFAULT now()
);
-- RLS intentionally disabled — search analytics insert from any user/anon

-- ──────────────────────────────────────────────────────────────────────────────
-- 26. analytics_events
-- Used by: lib/services.ts AnalyticsService
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.analytics_events (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    event_type text NOT NULL,
    user_id uuid REFERENCES auth.users(id),
    session_id text,
    product_id bigint REFERENCES public.products(id),
    order_id uuid REFERENCES public.orders(id),
    event_data jsonb,
    created_at timestamp DEFAULT now()
);
-- RLS intentionally disabled — analytics events insert broadly

-- ──────────────────────────────────────────────────────────────────────────────
-- 27. store_settings
-- Used by: admin/settings/page.tsx
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.store_settings (
    key text PRIMARY KEY,
    value jsonb NOT NULL,
    updated_at timestamptz DEFAULT now()
);
ALTER TABLE public.store_settings ENABLE ROW LEVEL SECURITY;

-- ──────────────────────────────────────────────────────────────────────────────
-- 28. email_queue
-- Used by: process-emails/route.ts
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.email_queue (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    email_type text NOT NULL,
    recipient_email text NOT NULL,
    recipient_name text,
    subject text NOT NULL,
    template_data jsonb,
    status text DEFAULT 'pending',
    error_message text,
    sent_at timestamp,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now()
);
ALTER TABLE public.email_queue ENABLE ROW LEVEL SECURITY;

-- ──────────────────────────────────────────────────────────────────────────────
-- 29. email_templates
-- Used by: process-emails/route.ts
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.email_templates (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    template_name text UNIQUE NOT NULL,
    subject text NOT NULL,
    html_body text NOT NULL,
    text_body text,
    variables jsonb,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now()
);
ALTER TABLE public.email_templates ENABLE ROW LEVEL SECURITY;

-- ──────────────────────────────────────────────────────────────────────────────
-- 30. email_campaigns
-- Used by: future admin marketing module
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.email_campaigns (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    name text NOT NULL,
    subject text NOT NULL,
    content text NOT NULL,
    sent_count integer DEFAULT 0,
    opened_count integer DEFAULT 0,
    clicked_count integer DEFAULT 0,
    status text DEFAULT 'draft',
    scheduled_at timestamp,
    sent_at timestamp,
    created_at timestamp DEFAULT now()
);
-- RLS intentionally disabled — admin only table

-- ──────────────────────────────────────────────────────────────────────────────
-- 31. newsletter_subscribers
-- Used by: lib/services.ts NewsletterService
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.newsletter_subscribers (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    email text UNIQUE NOT NULL,
    first_name text,
    user_id uuid REFERENCES auth.users(id),
    subscribed boolean DEFAULT true,
    subscription_source text,
    created_at timestamp DEFAULT now(),
    unsubscribed_at timestamp
);
ALTER TABLE public.newsletter_subscribers ENABLE ROW LEVEL SECURITY;

-- ──────────────────────────────────────────────────────────────────────────────
-- 32. abandoned_carts
-- Used by: lib/abandoned-cart.ts, cron/abandoned-carts/route.ts
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.abandoned_carts (
    id uuid DEFAULT extensions.uuid_generate_v4() PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id),
    cart_value numeric,
    items_count integer,
    email_sent_count integer DEFAULT 0,
    last_email_sent_at timestamp,
    recovered boolean DEFAULT false,
    recovered_at timestamp,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now()
);
ALTER TABLE public.abandoned_carts ENABLE ROW LEVEL SECURITY;

-- ──────────────────────────────────────────────────────────────────────────────
-- 33. audit_log
-- Used by: admin audit tracking
-- ──────────────────────────────────────────────────────────────────────────────
CREATE TABLE public.audit_log (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    admin_user_id uuid REFERENCES auth.users(id),
    action text NOT NULL,
    table_name text,
    record_id text,
    old_values jsonb,
    new_values jsonb,
    ip_address text,
    created_at timestamptz DEFAULT now()
);
ALTER TABLE public.audit_log ENABLE ROW LEVEL SECURITY;


-- ============================================================================
-- PHASE 3b: CREATE ALL POLICIES
-- All 33 tables now exist, so cross-references (e.g. user_roles) are safe.
-- ============================================================================

-- ── products policies ───────────────────────────────────────────────────────
CREATE POLICY "products_read_all" ON public.products FOR SELECT USING (
    is_active = true OR EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
);
CREATE POLICY "products_admin_insert" ON public.products FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
);
CREATE POLICY "products_admin_update" ON public.products FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
);
CREATE POLICY "products_admin_delete" ON public.products FOR DELETE USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
);

-- ── profiles policies ───────────────────────────────────────────────────────
CREATE POLICY "profiles_read_all" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "profiles_update_own" ON public.profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "profiles_insert_own" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

-- ── user_roles policies ─────────────────────────────────────────────────────
-- Only allow users to read their own role. Admin reads use service role client.
CREATE POLICY "user_roles_read_own" ON public.user_roles FOR SELECT USING (auth.uid() = user_id);

-- ── user_addresses policies ─────────────────────────────────────────────────
CREATE POLICY "addresses_own" ON public.user_addresses FOR ALL USING (auth.uid() = user_id);

-- ── product_images policies ─────────────────────────────────────────────────
CREATE POLICY "product_images_read_all" ON public.product_images FOR SELECT USING (true);
CREATE POLICY "product_images_admin_manage" ON public.product_images FOR ALL USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
);

-- ── product_videos policies ─────────────────────────────────────────────────
CREATE POLICY "product_videos_read_all" ON public.product_videos FOR SELECT USING (true);

-- ── product_inventory policies ──────────────────────────────────────────────
CREATE POLICY "inventory_read_all" ON public.product_inventory FOR SELECT USING (true);
CREATE POLICY "inventory_admin_manage" ON public.product_inventory FOR ALL USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
);
-- Service role bypasses RLS naturally — no blanket policy needed

-- ── cart_items policies ─────────────────────────────────────────────────────
CREATE POLICY "cart_own" ON public.cart_items FOR ALL USING (auth.uid() = user_id);

-- ── orders policies ─────────────────────────────────────────────────────────
CREATE POLICY "orders_own_read" ON public.orders FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "orders_admin_read" ON public.orders FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
);
CREATE POLICY "orders_admin_update" ON public.orders FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
);
-- Service role inserts/updates new orders — bypasses RLS naturally, no blanket policy needed
CREATE POLICY "orders_service_insert" ON public.orders FOR INSERT WITH CHECK (true);

-- ── order_items policies ────────────────────────────────────────────────────
CREATE POLICY "order_items_own_read" ON public.order_items FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.orders WHERE orders.id = order_id AND orders.user_id = auth.uid())
);
CREATE POLICY "order_items_admin_read" ON public.order_items FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
);
CREATE POLICY "order_items_service_insert" ON public.order_items FOR INSERT WITH CHECK (true);

-- ── coupons policies ────────────────────────────────────────────────────────
CREATE POLICY "coupons_read_active" ON public.coupons FOR SELECT USING (true);
CREATE POLICY "coupons_admin_manage" ON public.coupons FOR ALL USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
);

-- ── coupon_usage policies ───────────────────────────────────────────────────
CREATE POLICY "coupon_usage_own_read" ON public.coupon_usage FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "coupon_usage_service_insert" ON public.coupon_usage FOR INSERT WITH CHECK (true);

-- ── wishlist policies ───────────────────────────────────────────────────────
CREATE POLICY "wishlist_own" ON public.wishlist FOR ALL USING (auth.uid() = user_id);

-- ── product_reviews policies ────────────────────────────────────────────────
CREATE POLICY "reviews_read_approved" ON public.product_reviews FOR SELECT USING (true);
CREATE POLICY "reviews_insert_own" ON public.product_reviews FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "reviews_admin_manage" ON public.product_reviews FOR ALL USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
);

-- ── review_images policies ──────────────────────────────────────────────────
CREATE POLICY "review_images_read_all" ON public.review_images FOR SELECT USING (true);
CREATE POLICY "review_images_insert_own" ON public.review_images FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.product_reviews WHERE id = review_id AND user_id = auth.uid())
);

-- ── review_votes policies ───────────────────────────────────────────────────
CREATE POLICY "review_votes_own" ON public.review_votes FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "review_votes_read_all" ON public.review_votes FOR SELECT USING (true);

-- ── product_relations policies ──────────────────────────────────────────────
CREATE POLICY "product_relations_read_all" ON public.product_relations FOR SELECT USING (true);
CREATE POLICY "product_relations_admin_manage" ON public.product_relations FOR ALL USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
);

-- ── product_views policies ──────────────────────────────────────────────────
CREATE POLICY "product_views_insert_any" ON public.product_views FOR INSERT WITH CHECK (true);
CREATE POLICY "product_views_read_own" ON public.product_views FOR SELECT USING (auth.uid() = user_id);

-- ── price_changes policies ──────────────────────────────────────────────────
CREATE POLICY "price_changes_read_all" ON public.price_changes FOR SELECT USING (true);

-- ── loyalty_points policies ─────────────────────────────────────────────────
CREATE POLICY "loyalty_points_own" ON public.loyalty_points FOR ALL USING (auth.uid() = user_id);

-- ── loyalty_transactions policies ───────────────────────────────────────────
CREATE POLICY "loyalty_txns_own" ON public.loyalty_transactions FOR ALL USING (auth.uid() = user_id);

-- ── return_requests policies ────────────────────────────────────────────────
CREATE POLICY "returns_own" ON public.return_requests FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "returns_admin_read" ON public.return_requests FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
);
CREATE POLICY "returns_admin_update" ON public.return_requests FOR UPDATE USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
);

-- ── return_items policies ───────────────────────────────────────────────────
CREATE POLICY "return_items_own" ON public.return_items FOR ALL USING (
    EXISTS (SELECT 1 FROM public.return_requests WHERE id = return_request_id AND user_id = auth.uid())
);

-- ── saved_for_later policies ────────────────────────────────────────────────
CREATE POLICY "saved_own" ON public.saved_for_later FOR ALL USING (auth.uid() = user_id);

-- ── store_settings policies ─────────────────────────────────────────────────
CREATE POLICY "settings_read_all" ON public.store_settings FOR SELECT USING (true);
CREATE POLICY "settings_admin_manage" ON public.store_settings FOR ALL USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
);

-- ── email_queue policies ────────────────────────────────────────────────────
CREATE POLICY "email_queue_admin_read" ON public.email_queue FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
);
CREATE POLICY "email_queue_service_manage" ON public.email_queue FOR ALL USING (true);

-- ── email_templates policies ────────────────────────────────────────────────
CREATE POLICY "email_templates_read_all" ON public.email_templates FOR SELECT USING (true);

-- ── newsletter_subscribers policies ─────────────────────────────────────────
CREATE POLICY "newsletter_insert_any" ON public.newsletter_subscribers FOR INSERT WITH CHECK (true);
CREATE POLICY "newsletter_own" ON public.newsletter_subscribers FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "newsletter_admin_read" ON public.newsletter_subscribers FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
);

-- ── abandoned_carts policies ────────────────────────────────────────────────
CREATE POLICY "abandoned_carts_own" ON public.abandoned_carts FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "abandoned_carts_service" ON public.abandoned_carts FOR SELECT USING (true);

-- ── audit_log policies ──────────────────────────────────────────────────────
CREATE POLICY "audit_admin_read" ON public.audit_log FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role = 'admin')
);
CREATE POLICY "audit_service_insert" ON public.audit_log FOR INSERT WITH CHECK (true);


-- ============================================================================
-- PHASE 4: VIEWS
-- ============================================================================

-- low_stock_products (lib/inventory.ts getLowStockProducts)
CREATE OR REPLACE VIEW public.low_stock_products AS
SELECT
    pi.id,
    pi.product_id,
    pi.size,
    pi.stock_quantity,
    pi.low_stock_threshold,
    pi.reserved_quantity,
    p.name AS product_name,
    p.front_image
FROM public.product_inventory pi
JOIN public.products p ON p.id = pi.product_id
WHERE pi.stock_quantity <= pi.low_stock_threshold;

-- top_selling_products (lib/recommendations.ts getBestSellers)
CREATE OR REPLACE VIEW public.top_selling_products AS
SELECT
    p.id,
    p.name,
    COALESCE(SUM(oi.quantity), 0) AS total_sold
FROM public.products p
LEFT JOIN public.order_items oi ON oi.product_id = p.id
LEFT JOIN public.orders o ON o.id = oi.order_id AND o.status IN ('confirmed', 'shipped', 'delivered')
GROUP BY p.id, p.name
ORDER BY total_sold DESC;

-- products_with_ratings (lib/search.ts advancedProductSearch)
CREATE OR REPLACE VIEW public.products_with_ratings AS
SELECT
    p.*,
    COALESCE(AVG(pr.rating), 0) AS average_rating,
    COUNT(pr.id) AS review_count
FROM public.products p
LEFT JOIN public.product_reviews pr ON pr.product_id = p.id AND pr.is_approved = true
GROUP BY p.id;


-- ============================================================================
-- PHASE 5: RPC FUNCTIONS
-- ============================================================================

-- increment_coupon_usage (by code — verify/route.ts)
CREATE OR REPLACE FUNCTION public.increment_coupon_usage(p_coupon_code text)
RETURNS void AS $$
BEGIN
    UPDATE public.coupons
    SET used_count = COALESCE(used_count, 0) + 1
    WHERE code = p_coupon_code;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- increment_coupon_usage (by id — lib/coupons.ts)
CREATE OR REPLACE FUNCTION public.increment_coupon_usage(p_coupon_id uuid)
RETURNS void AS $$
BEGIN
    UPDATE public.coupons
    SET used_count = COALESCE(used_count, 0) + 1
    WHERE id = p_coupon_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- reserve_product_stock (lib/inventory.ts)
CREATE OR REPLACE FUNCTION public.reserve_product_stock(
    p_product_id bigint, p_size text, p_quantity integer
) RETURNS void AS $$
BEGIN
    UPDATE public.product_inventory
    SET reserved_quantity = reserved_quantity + p_quantity,
        updated_at = now()
    WHERE product_id = p_product_id AND size = p_size
      AND stock_quantity - reserved_quantity >= p_quantity;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Insufficient stock for product % size %', p_product_id, p_size;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- release_product_stock (lib/inventory.ts)
CREATE OR REPLACE FUNCTION public.release_product_stock(
    p_product_id bigint, p_size text, p_quantity integer
) RETURNS void AS $$
BEGIN
    UPDATE public.product_inventory
    SET reserved_quantity = GREATEST(reserved_quantity - p_quantity, 0),
        updated_at = now()
    WHERE product_id = p_product_id AND size = p_size;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- decrement_inventory_rpc (lib/inventory.ts, verify/route.ts)
CREATE OR REPLACE FUNCTION public.decrement_inventory_rpc(
    p_product_id bigint, p_size text, p_quantity integer
) RETURNS void AS $$
BEGIN
    UPDATE public.product_inventory
    SET stock_quantity = GREATEST(stock_quantity - p_quantity, 0),
        sold_quantity = sold_quantity + p_quantity,
        updated_at = now()
    WHERE product_id = p_product_id AND size = p_size;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- increment_inventory (lib/returns.ts — restock on approved return)
CREATE OR REPLACE FUNCTION public.increment_inventory(
    p_product_id bigint, p_size text, p_quantity integer
) RETURNS void AS $$
BEGIN
    UPDATE public.product_inventory
    SET stock_quantity = stock_quantity + p_quantity,
        sold_quantity = GREATEST(sold_quantity - p_quantity, 0),
        updated_at = now()
    WHERE product_id = p_product_id AND size = p_size;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- update_review_helpful_count (lib/reviews.ts)
CREATE OR REPLACE FUNCTION public.update_review_helpful_count(
    p_review_id uuid, p_is_helpful boolean, p_delta integer
) RETURNS void AS $$
BEGIN
    IF p_is_helpful THEN
        UPDATE public.product_reviews
        SET helpful_count = helpful_count + p_delta
        WHERE id = p_review_id;
    ELSE
        UPDATE public.product_reviews
        SET not_helpful_count = not_helpful_count + p_delta
        WHERE id = p_review_id;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- increment_abandoned_cart_emails (lib/abandoned-cart.ts)
CREATE OR REPLACE FUNCTION public.increment_abandoned_cart_emails(cart_id uuid)
RETURNS void AS $$
BEGIN
    UPDATE public.abandoned_carts
    SET email_sent_count = email_sent_count + 1,
        last_email_sent_at = now()
    WHERE id = cart_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- ============================================================================
-- PHASE 6: AUTH TRIGGER — Auto-create profile on new user
-- ============================================================================

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
    INSERT INTO public.profiles (id, email, full_name, role)
    VALUES (
        NEW.id,
        NEW.email,
        COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
        'customer'
    )
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_new_user();


-- ============================================================================
-- PHASE 7: BACKFILL — Create profiles for existing users
-- ============================================================================

INSERT INTO public.profiles (id, email, full_name, role)
SELECT
    u.id,
    u.email,
    COALESCE(u.raw_user_meta_data->>'full_name', ''),
    COALESCE(r.role, 'customer')
FROM auth.users u
LEFT JOIN public.user_roles r ON r.user_id = u.id
ON CONFLICT (id) DO NOTHING;


-- ============================================================================
-- PHASE 8: SEED store_settings DEFAULTS
-- ============================================================================

INSERT INTO public.store_settings (key, value) VALUES
  ('store_name', '"HAXEUS"'),
  ('store_email', '"haxeus.in@gmail.com"'),
  ('currency', '"INR"'),
  ('shipping_rate', '150'),
  ('free_shipping_above', '2000'),
  ('cod_enabled', 'false'),
  ('support_email', '"haxeus.in@gmail.com"'),
  ('support_url', '"mailto:haxeus.in@gmail.com"')
ON CONFLICT (key) DO NOTHING;


-- ============================================================================
-- PHASE 9: ADMIN USER ROLE
-- ============================================================================
-- IMPORTANT: Replace with your actual admin user UUID from Supabase Auth > Users
-- Uncomment the line below and fill in your admin UUID after running this migration:
-- INSERT INTO public.user_roles (user_id, role) VALUES ('YOUR-ADMIN-UUID-HERE', 'admin');
